all:
  children:
    control_plane:
      hosts:
        control-plane-0.proxmox.arcdsc.com:
          ansible_host: 10.10.10.30
    worker_nodes:
      hosts:
        worker-0.proxmox.arcdsc.com:
          ansible_host: 10.10.10.40
        worker-1.proxmox.arcdsc.com:
          ansible_host: 10.10.10.41
        worker-2.proxmox.arcdsc.com:
          ansible_host: 10.10.10.42
  vars:
    ansible_user: "ansible"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'